image: openjdk:8-jdk

stages:
  - build
  - publish

###################
# Build
###################
.build-jar:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 5 minute


###################
# Publish
###################
push-jar:
  stage: publish
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - mkdir .gradle
    - echo "$GPG_KEY_PRIVATE" > $GRADLE_USER_HOME/private.key
    - gpg --import $GRADLE_USER_HOME/private.key
    - echo "$GRADLE_PROPERTIES" > $GRADLE_USER_HOME/gradle.properties
    - ./gradlew assemble