image: openjdk:8-jdk

stages:
  - build
  - publish

cache:
  paths:
    - build/
    - .gradle/wrapper
    - .gradle/caches

###################
# Build
###################
build-jar:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - mkdir .gradle
    - echo "$GRADLE_PROPERTIES3" > $GRADLE_USER_HOME/gradle.properties
    - ./gradlew assemble


###################
# Publish
###################
push-jar:
  stage: publish
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - mkdir .gradle
    - echo "$GPG_KEY_PRIVATE" > private.key
    - gpg --import private.key
    - gpg --export-secret-keys -o secring.gpg
    - echo "$GRADLE_PROPERTIES3" > $GRADLE_USER_HOME/gradle.properties
    - ./gradlew -Psign uploadArchives