image: openjdk:8-jdk

stages:
  - build
  - publish

###################
# Build
###################
.build-jar:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 5 minute


###################
# Publish
###################
build-jar:
  stage: publish
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - echo "$GPG_KEY_PRIVATE" > private.key
    - echo "$GPG_KEY_PUBLIC" > public.key
    - gpg --import public.key
    - gpg --import private.key
    - gpg -K
